const List<Map<String, dynamic>> synAntSetUpExercise = [
  {
    "exercise_id": "Game_2_ex_1",
    "game_key": 2,
    "description": "Match synonyms and antonyms with provided words"
  },
];

const List<Map<String, dynamic>> synAntSetUpQuestions = [
  {"word": "powerless", "synonyms": [""], "antonyms": ["powerful"]},
  {"word": "understandability", "synonyms": ["comprehensibility"], "antonyms": [""]},
  {"word": "large", "synonyms": ["big", "huge"], "antonyms": ["tiny", "small"]},
  {"word": "swimmingly", "synonyms": ["smoothly"], "antonyms": [""]},
  {"word": "soothe", "synonyms": ["comfort", "solace"], "antonyms": [""]},
  {"word": "get off the ground", "synonyms": ["take off"], "antonyms": [""]},
  {"word": "as much as possible", "synonyms": ["as far as possible"], "antonyms": [""]},
  {"word": "clock up", "synonyms": ["log up"], "antonyms": [""]},
  {"word": "outguess", "synonyms": ["second-guess"], "antonyms": [""]},
  {"word": "unhopeful", "synonyms": ["abject"], "antonyms": ["hopeful"]},
  {"word": "staidly", "synonyms": ["gravely", "soberly"], "antonyms": [""]},
  {"word": "strangulation", "synonyms": ["choking", "strangling", "throttling"], "antonyms": [""]},
  {"word": "exultation", "synonyms": ["jubilation", "rejoicing"], "antonyms": [""]},
  {"word": "denuded", "synonyms": ["bald", "denudate"], "antonyms": [""]},
  {"word": "behold", "synonyms": ["lay eyes on"], "antonyms": [""]},
  {"word": "oversize", "synonyms": ["outsize"], "antonyms": [""]},
  {"word": "delineate", "synonyms": ["define"], "antonyms": [""]},
  {"word": "concurrently", "synonyms": ["at the same time"], "antonyms": [""]},
  {"word": "whimsical", "synonyms": ["impulsive"], "antonyms": [""]},
  {"word": "unsporting", "synonyms": ["cheating", "dirty", "foul", "unsportsmanlike"], "antonyms": [""]},
  {"word": "at present", "synonyms": ["now", "currently"], "antonyms": [""]},
  {"word": "gross out", "synonyms": ["disgust", "repel", "revolt"], "antonyms": [""]},
  {"word": "stand still", "synonyms": [""], "antonyms": ["move"]},
  {"word": "please", "synonyms": ["delight"], "antonyms": ["displease"]},
  {"word": "vim", "synonyms": ["energy", "muscularity", "vigour"], "antonyms": ["faint", "weak"]},
  {"word": "stab", "synonyms": ["jab"], "antonyms": [""]},
  {"word": "intimate", "synonyms": ["cozy", "informal"], "antonyms": ["formal"]},
  {"word": "controversial", "synonyms": [""], "antonyms": ["uncontroversial"]},
  {"word": "weather forecaster", "synonyms": ["weatherman"], "antonyms": [""]},
  {"word": "at bay", "synonyms": ["cornered", "trapped", "treed"], "antonyms": [""]},
  {"word": "jolted", "synonyms": ["shaken"], "antonyms": [""]},
  {"word": "educatee", "synonyms": ["pupil", "student"], "antonyms": [""]},
  {"word": "blasted", "synonyms": ["blamed", "damned", "darned", "goddamned"], "antonyms": [""]},
  {"word": "staleness", "synonyms": ["triteness"], "antonyms": [""]},
  {"word": "bear away", "synonyms": ["bear off", "carry away", "carry off", "take away"], "antonyms": [""]},
  {"word": "dell", "synonyms": ["dingle"], "antonyms": [""]},
  {"word": "unambiguous", "synonyms": ["unique"], "antonyms": ["ambiguous"]},
  {"word": "go after", "synonyms": ["chase", "trail"], "antonyms": ["let sth go"]},
  {"word": "limpid", "synonyms": ["liquid"], "antonyms": [""]},
  {"word": "vocabulary", "synonyms": ["lexicon"], "antonyms": [""]},
  {"word": "unspeakable", "synonyms": ["unnameable", "unutterable"], "antonyms": [""]},
  {"word": "strikingness", "synonyms": ["boldness"], "antonyms": [""]},
  {"word": "any longer", "synonyms": ["anymore"], "antonyms": [""]},
  {"word": "favorite", "synonyms": ["best-loved", "preferred"], "antonyms": ["least liked"]},
  {"word": "let up", "synonyms": ["ease off", "ease up"], "antonyms": [""]},
  {"word": "injure", "synonyms": ["hurt", "wound"], "antonyms": ["heal"]},
  {"word": "hazardously", "synonyms": ["dangerously", "perilously"], "antonyms": [""]},
  {"word": "diffident", "synonyms": ["shy", "timid", "unsure"], "antonyms": ["confident"]},
  {"word": "rightful", "synonyms": ["lawful", "true"], "antonyms": ["false"]},
  {"word": "lighted", "synonyms": ["illuminated"], "antonyms": ["unlit"]}
];